version: "3.9"

networks:
  anivoy-shared-net:
    external: true

services:
  service-name:
    build:
      context: .
      target: development
    container_name: anivoy-file-service
    ports:
      - "6069:6069"
    env_file:
      - .env
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - anivoy-shared-net
